FROM python:3.11-slim

WORKDIR /app

# dipendenze
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copia TUTTO il progetto
COPY . .

# genera protobuf
RUN python -m grpc_tools.protoc \
    -I. \
    --python_out=. \
    --grpc_python_out=. \
    proto/rf_v2.proto

# storage condiviso
RUN mkdir -p /mnt/efs/gp_artifacts

EXPOSE 50051

CMD ["python", "master.py"]