version: "3.9"

services:
  gp-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: gp-master
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env.master
    volumes:
      - /mnt/efs/gp_artifacts:/mnt/efs/gp_artifacts
    profiles:
      - master

  gp-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: gp-worker
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env.worker
    volumes:
      - /mnt/efs/gp_artifacts:/mnt/efs/gp_artifacts
    profiles:
      - worker