FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY master.py .

RUN mkdir -p /shared/artifacts

EXPOSE 50051

CMD ["python", "master.py"]