FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY rf.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. rf.proto

COPY worker.py .

RUN mkdir -p /shared/artifacts

EXPOSE 50061

CMD ["python", "worker.py"]