FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python -m grpc_tools.protoc \
    -I./proto \
    --python_out=/app \
    --grpc_python_out=/app \
    ./proto/rf_v2.proto

RUN mkdir -p /mnt/efs/gp_artifacts

EXPOSE 50061

CMD ["python", "worker.py"]