# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rf_v2_pb2 as rf__v2__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rf_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/distributedrf.CoordinatorService/RegisterWorker',
                request_serializer=rf__v2__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/distributedrf.CoordinatorService/Heartbeat',
                request_serializer=rf__v2__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.SubmitTraining = channel.unary_unary(
                '/distributedrf.CoordinatorService/SubmitTraining',
                request_serializer=rf__v2__pb2.SubmitTrainingRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.SubmitTrainingResponse.FromString,
                _registered_method=True)
        self.ResumeTraining = channel.unary_unary(
                '/distributedrf.CoordinatorService/ResumeTraining',
                request_serializer=rf__v2__pb2.ResumeTrainingRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.ResumeTrainingResponse.FromString,
                _registered_method=True)
        self.SubmitInference = channel.unary_unary(
                '/distributedrf.CoordinatorService/SubmitInference',
                request_serializer=rf__v2__pb2.SubmitInferenceRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.SubmitInferenceResponse.FromString,
                _registered_method=True)
        self.DownloadModel = channel.unary_unary(
                '/distributedrf.CoordinatorService/DownloadModel',
                request_serializer=rf__v2__pb2.DownloadModelRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.DownloadModelResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/distributedrf.CoordinatorService/GetJobStatus',
                request_serializer=rf__v2__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)
        self.ListExperiments = channel.unary_unary(
                '/distributedrf.CoordinatorService/ListExperiments',
                request_serializer=rf__v2__pb2.ListExperimentsRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.ListExperimentsResponse.FromString,
                _registered_method=True)
        self.CountSavedTrees = channel.unary_unary(
                '/distributedrf.CoordinatorService/CountSavedTrees',
                request_serializer=rf__v2__pb2.CountSavedTreesRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.CountSavedTreesResponse.FromString,
                _registered_method=True)
        self.GetValidationMetrics = channel.unary_unary(
                '/distributedrf.CoordinatorService/GetValidationMetrics',
                request_serializer=rf__v2__pb2.GetValidationMetricsRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.GetValidationMetricsResponse.FromString,
                _registered_method=True)
        self.RunInferenceOnModelSplit = channel.unary_unary(
                '/distributedrf.CoordinatorService/RunInferenceOnModelSplit',
                request_serializer=rf__v2__pb2.RunInferenceOnModelSplitRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.RunInferenceOnModelSplitResponse.FromString,
                _registered_method=True)
        self.ResetSharedArtifacts = channel.unary_unary(
                '/distributedrf.CoordinatorService/ResetSharedArtifacts',
                request_serializer=rf__v2__pb2.ResetSharedArtifactsRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.ResetSharedArtifactsResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExperiments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountSavedTrees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValidationMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunInferenceOnModelSplit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetSharedArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=rf__v2__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=rf__v2__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=rf__v2__pb2.HeartbeatRequest.FromString,
                    response_serializer=rf__v2__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SubmitTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTraining,
                    request_deserializer=rf__v2__pb2.SubmitTrainingRequest.FromString,
                    response_serializer=rf__v2__pb2.SubmitTrainingResponse.SerializeToString,
            ),
            'ResumeTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeTraining,
                    request_deserializer=rf__v2__pb2.ResumeTrainingRequest.FromString,
                    response_serializer=rf__v2__pb2.ResumeTrainingResponse.SerializeToString,
            ),
            'SubmitInference': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitInference,
                    request_deserializer=rf__v2__pb2.SubmitInferenceRequest.FromString,
                    response_serializer=rf__v2__pb2.SubmitInferenceResponse.SerializeToString,
            ),
            'DownloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=rf__v2__pb2.DownloadModelRequest.FromString,
                    response_serializer=rf__v2__pb2.DownloadModelResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=rf__v2__pb2.GetJobStatusRequest.FromString,
                    response_serializer=rf__v2__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'ListExperiments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExperiments,
                    request_deserializer=rf__v2__pb2.ListExperimentsRequest.FromString,
                    response_serializer=rf__v2__pb2.ListExperimentsResponse.SerializeToString,
            ),
            'CountSavedTrees': grpc.unary_unary_rpc_method_handler(
                    servicer.CountSavedTrees,
                    request_deserializer=rf__v2__pb2.CountSavedTreesRequest.FromString,
                    response_serializer=rf__v2__pb2.CountSavedTreesResponse.SerializeToString,
            ),
            'GetValidationMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValidationMetrics,
                    request_deserializer=rf__v2__pb2.GetValidationMetricsRequest.FromString,
                    response_serializer=rf__v2__pb2.GetValidationMetricsResponse.SerializeToString,
            ),
            'RunInferenceOnModelSplit': grpc.unary_unary_rpc_method_handler(
                    servicer.RunInferenceOnModelSplit,
                    request_deserializer=rf__v2__pb2.RunInferenceOnModelSplitRequest.FromString,
                    response_serializer=rf__v2__pb2.RunInferenceOnModelSplitResponse.SerializeToString,
            ),
            'ResetSharedArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSharedArtifacts,
                    request_deserializer=rf__v2__pb2.ResetSharedArtifactsRequest.FromString,
                    response_serializer=rf__v2__pb2.ResetSharedArtifactsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributedrf.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributedrf.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/RegisterWorker',
            rf__v2__pb2.RegisterWorkerRequest.SerializeToString,
            rf__v2__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/Heartbeat',
            rf__v2__pb2.HeartbeatRequest.SerializeToString,
            rf__v2__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/SubmitTraining',
            rf__v2__pb2.SubmitTrainingRequest.SerializeToString,
            rf__v2__pb2.SubmitTrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/ResumeTraining',
            rf__v2__pb2.ResumeTrainingRequest.SerializeToString,
            rf__v2__pb2.ResumeTrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/SubmitInference',
            rf__v2__pb2.SubmitInferenceRequest.SerializeToString,
            rf__v2__pb2.SubmitInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/DownloadModel',
            rf__v2__pb2.DownloadModelRequest.SerializeToString,
            rf__v2__pb2.DownloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/GetJobStatus',
            rf__v2__pb2.GetJobStatusRequest.SerializeToString,
            rf__v2__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExperiments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/ListExperiments',
            rf__v2__pb2.ListExperimentsRequest.SerializeToString,
            rf__v2__pb2.ListExperimentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountSavedTrees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/CountSavedTrees',
            rf__v2__pb2.CountSavedTreesRequest.SerializeToString,
            rf__v2__pb2.CountSavedTreesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValidationMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/GetValidationMetrics',
            rf__v2__pb2.GetValidationMetricsRequest.SerializeToString,
            rf__v2__pb2.GetValidationMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunInferenceOnModelSplit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/RunInferenceOnModelSplit',
            rf__v2__pb2.RunInferenceOnModelSplitRequest.SerializeToString,
            rf__v2__pb2.RunInferenceOnModelSplitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetSharedArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/ResetSharedArtifacts',
            rf__v2__pb2.ResetSharedArtifactsRequest.SerializeToString,
            rf__v2__pb2.ResetSharedArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainShard = channel.unary_unary(
                '/distributedrf.WorkerService/TrainShard',
                request_serializer=rf__v2__pb2.TrainShardRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.TrainShardResponse.FromString,
                _registered_method=True)
        self.PredictShard = channel.unary_unary(
                '/distributedrf.WorkerService/PredictShard',
                request_serializer=rf__v2__pb2.PredictShardRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.PredictShardResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainShard': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainShard,
                    request_deserializer=rf__v2__pb2.TrainShardRequest.FromString,
                    response_serializer=rf__v2__pb2.TrainShardResponse.SerializeToString,
            ),
            'PredictShard': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictShard,
                    request_deserializer=rf__v2__pb2.PredictShardRequest.FromString,
                    response_serializer=rf__v2__pb2.PredictShardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributedrf.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributedrf.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.WorkerService/TrainShard',
            rf__v2__pb2.TrainShardRequest.SerializeToString,
            rf__v2__pb2.TrainShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.WorkerService/PredictShard',
            rf__v2__pb2.PredictShardRequest.SerializeToString,
            rf__v2__pb2.PredictShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
