# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rf_v2_pb2 as rf__v2__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rf_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/distributedrf.CoordinatorService/RegisterWorker',
                request_serializer=rf__v2__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/distributedrf.CoordinatorService/Heartbeat',
                request_serializer=rf__v2__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.SubmitTraining = channel.unary_unary(
                '/distributedrf.CoordinatorService/SubmitTraining',
                request_serializer=rf__v2__pb2.SubmitTrainingRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.SubmitTrainingResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=rf__v2__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=rf__v2__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=rf__v2__pb2.HeartbeatRequest.FromString,
                    response_serializer=rf__v2__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SubmitTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTraining,
                    request_deserializer=rf__v2__pb2.SubmitTrainingRequest.FromString,
                    response_serializer=rf__v2__pb2.SubmitTrainingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributedrf.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributedrf.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/RegisterWorker',
            rf__v2__pb2.RegisterWorkerRequest.SerializeToString,
            rf__v2__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/Heartbeat',
            rf__v2__pb2.HeartbeatRequest.SerializeToString,
            rf__v2__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.CoordinatorService/SubmitTraining',
            rf__v2__pb2.SubmitTrainingRequest.SerializeToString,
            rf__v2__pb2.SubmitTrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainShard = channel.unary_unary(
                '/distributedrf.WorkerService/TrainShard',
                request_serializer=rf__v2__pb2.TrainShardRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.TrainShardResponse.FromString,
                _registered_method=True)
        self.PredictShard = channel.unary_unary(
                '/distributedrf.WorkerService/PredictShard',
                request_serializer=rf__v2__pb2.PredictShardRequest.SerializeToString,
                response_deserializer=rf__v2__pb2.PredictShardResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainShard': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainShard,
                    request_deserializer=rf__v2__pb2.TrainShardRequest.FromString,
                    response_serializer=rf__v2__pb2.TrainShardResponse.SerializeToString,
            ),
            'PredictShard': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictShard,
                    request_deserializer=rf__v2__pb2.PredictShardRequest.FromString,
                    response_serializer=rf__v2__pb2.PredictShardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributedrf.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributedrf.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.WorkerService/TrainShard',
            rf__v2__pb2.TrainShardRequest.SerializeToString,
            rf__v2__pb2.TrainShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedrf.WorkerService/PredictShard',
            rf__v2__pb2.PredictShardRequest.SerializeToString,
            rf__v2__pb2.PredictShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
